### ISSUE TITLE
@page로 경로 지정이 안되는 문제

### ISSUE THREAD

**Issue by gongbj0113** [HeXA-UNIST/hexa-homepage-frontend#8]
tsconfig.json 파일에
```
...
"compilerOptions": {
    ...
     "baseUrl": "./src" /* Specify the base directory to resolve non-relative module names. */,
    "paths": {
      "@page/*":["./src/pages/*"],
      "@css/*" : ["./src/static/css/*"],
      "@img/*" : ["./src/static/img/*"],
      "@model/*" : ["./src/models/*"],
      "@component/*" : ["./src/common/components/*"],
    },
    ...
}
...
```

이렇게 했지만
`import Banner from "@page/home/sections/Banner"`
하면 오류가 뜹니다..

` "@page/*":["pages/*"],` 이렇게도 해 봤지만 동일하게 안됩니다

**Comment by lafest** [comment]
검색해보니 create-react-app으로 만들어진 프로젝트는 `npm start`를 실행할 때 마다  웹팩 빌드 과정에서 tsconfig.json을 기본값으로 변경해서 발생하는 문제라고 합니다. ([ref1](https://plusreturn.com/blog/how-to-configure-a-path-alias-in-a-react-typescript-app-for-cleaner-imports/), [ref2](https://blog.haneul-lee.com/2021/05/create-react-app-%EC%A0%88%EB%8C%80%EA%B2%BD%EB%A1%9C-%EC%84%A4%EC%A0%95-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8/))
방법이 2가지인데...
1. `npm eject`를 실행해서 웹팩 설정을 직접 바꾸기
2.  [craco](https://www.npmjs.com/package/@craco/craco) 사용해서 cra 설정 오버라이딩하기

아무래도 웹팩 설정을 직접 세팅하는 것이 복잡하다보니 2번 방법이 좋을 것 같아요.
